import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";
import BottomNav from "@/components/bottom-nav";
import { ThemeProvider } from "@/components/theme-provider";
import { cookies } from "next/headers";
import { THEME_PARAM } from "./constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get(THEME_PARAM)?.value || "system";

  return (
    <html lang="en" className={theme}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Navbar />
          <main className="bg-background container max-w-7xl mx-auto px-4 pb-24 pt-4">
            {children}
          </main>
          <BottomNav />
          {/* <Footer /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
